codecov:
  bot: "codecov-io"
  strict_yaml_branch: "main" # or your default branch
  require_ci_to_pass: no # set to no for testing
  notify:
    after_n_builds: 1 # check immediately for testing
    wait_for_ci: yes
  max_report_age: off

ignore:
  - "src/database/migrations/**"
  - "src/database/seeds/**"
  - "**/*.module.ts"

coverage:
  precision: 2
  round: nearest
  range: 30...100
  status:
    project:
      default:
        informational: true
        target: 99%
        threshold: 30%
        if_ci_failed: error
    patch:
      default:
        informational: true
        target: 70%
        threshold: 5%
    changes: false

github_checks:
  annotations: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false

comment:
  layout: header, diff
  require_changes: false
  behavior: default
  after_n_builds: 1 # check immediately for testing
