services:
  dcp-api:
    image: dcp-api
    container_name: dcp-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    networks:
      - dcp-network

  db:
    image: postgres:16
    container_name: dcp-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dcp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
    ports:
      - "25432:5432"
    networks:
      - dcp-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "18080:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@decodex.net
      PGADMIN_DEFAULT_PASSWORD: Password1!
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    networks:
      - dcp-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  dcp-network:
    driver: bridge